module App {
    export var TagList = [
        "Functions and Notions. Numbers",
        "Functions and Notions. Prices",
        "Functions and Notions. Telling the time",
        "Functions and Notions. Directions",
        "Functions and Notions. Greetings",
        "Functions and Notions. Giving personal information",
        "Functions and Notions. Describing habits and routines",
        "Functions and Notions. Describing people",
        "Functions and Notions. Describing things",
        "Functions and Notions. Requests",
        "Functions and Notions. Suggestions",
        "Functions and Notions. Advice",
        "Functions and Notions. Invitations",
        "Functions and Notions. Offers",
        "Functions and Notions. Arrangements to meet people",
        "Functions and Notions. Obligations and necessity",
        "Functions and Notions. Describing places",
        "Functions and Notions. Describing past experiences and storytelling",
        "Functions and Notions. Describing feelings, emotions, attitudes",
        "Functions and Notions. Describing feelings, emotion, attitudes precisely",
        "Functions and Notions. Describing hopes and plans",
        "Functions and Notions. Giving precise information",
        "Functions and Notions. Expressing abstract ideas",
        "Functions and Notions. Expressing certainty, probability, doubt",
        "Functions and Notions. Generalising and qualifying",
        "Functions and Notions. Synthesizing, evaluating, glossing information",
        "Functions and Notions. Speculating",
        "Functions and Notions. Speculating and hypothesising about causes, consequences etc.",
        "Functions and Notions. Expressing opinions",
        "Functions and Notions. Expressing opinions tentatively, hedging",
        "Functions and Notions. Expressing shades of opinion and certainty",
        "Functions and Notions. Expressing agreement/disagreement",
        "Functions and Notions. Expressing reaction, e.g. indifference",
        "Functions and Notions. Critiquing and reviewing. Talking about films and books",
        "Functions and Notions. Critiquing and reviewing",
        "Functions and Notions. Developing an argument",
        "Functions and Notions. Developing an argument in academic discourse style",
        "Functions and Notions. Developing an argument systematically",
        "Functions and Notions. Conceding a point",
        "Functions and Notions. Emphasizing a point, feeling, issue",
        "Functions and Notions. Defending a point of view persuasively",
        "Functions and Notions. Responding to counterarguments",
        "Discourse Functions. Initiating conversation",
        "Discourse Functions. Closing conversation",
        "Discourse Functions. Checking understanding from speaker's point of view",
        "Discourse Functions. Checking understanding from listener's point of view",
        "Discourse Functions. Managing interaction. Interrupting",
        "Discourse Functions. Managing interaction. Changing the topic",
        "Discourse Functions. Managing interaction. Resuming",
        "Discourse Functions. Managing interaction. Continuing",
        "Discourse Functions. Taking the initiative in interaction. Control and delegation at start",
        "Discourse Functions. Taking the initiative in interaction. During the meeting",
        "Discourse Functions. Taking the initiative in interaction. Keeping interaction participants on topic",
        "Discourse Functions. Taking initiative in non-control situation",
        "Discourse Functions. Encouraging another speaker to continue.",
        "Discourse Functions. Inviting another speaker to come in in one-to-one interaction",
        "Discourse Functions. Inviting another speaker to come in in group interaction.",
        "Discourse Functions. Interacting informally, reacting, expressing interest, sympathy, surprise",
        "Discourse Markers. Connecting words (and, but, because)",
        "Discourse Markers. Linkers: sequential - past time (first, finally)",
        "Discourse Markers. Linkers: sequential - past time (later)",
        "Discourse Markers. Linkers: sequential - past time (subsequently)",
        "Discourse Markers. Connecting words expressing cause and effect, contrast etc.",
        "Discourse Markers. Linkers: although, in spite of, despite",
        "Discourse Markers. Linking devices: logical markers",
        "Discourse Markers. Markers to structure informal spoken discourse",
        "Discourse Markers. Discourse markers to structure formal speech",
        "Discourse Markers. Markers to structure and signpost informal speech and writing",
        "Simple Verb Forms. To be (including questions and negatives)",
        "Simple Verb Forms. Have got (British)",
        "Simple Verb Forms. Imperatives (+/-)",
        "Questions. Questions forms",
        "Questions. Wh-questions in the past",
        "Questions. Complex question tags",
        "Present. Present simple",
        "Present. Present continuous",
        "Past. Past simple",
        "Past. Past simple (narrative)",
        "Past. Past simple (to be)",
        "Past. Past continuous",
        "Past. Past continuous (narrative)",
        "Past. Used to",
        "Past. Used to (narrative)",
        "Past. Would expressing habit in the past",
        "Past. Would expressing habit in the past (narrative)",
        "Past. Past perfect",
        "Past. Past perfect (narrative)",
        "Past. Past perfect continuous",
        "Past. Past perfect continuous (narrative)",
        "Future. Going to",
        "Future. Present continuous for the future (arrangements)",
        "Future. Future time (will, going to)",
        "Future. Future time (will, going to) (Prediction)",
        "Future. Future continuous",
        "Future. Future continuous (Prediction)",
        "Future. Future perfect",
        "Future. Future perfect (Prediction)",
        "Future. Future perfect continuous",
        "Future. Future perfect continuous (Prediction)",
        "Present Perfect. Present perfect",
        "Present Perfect. Present perfect, past simple",
        "Present Perfect. Present perfect continuous",
        "Gerund and Infinitive. I'd like",
        "Gerund and Infinitive. Gerunds",
        "Gerund and Infinitive. Verb + -ing (like/hate/love)",
        "Gerund and Infinitive. Verb + -ing/infinitive (like / want - would like)",
        "Gerund and Infinitive. To + infinitive (express purpose)",
        "Gerund and Infinitive. Verb + to + infinitive",
        "Conditionals. Zero and first conditional",
        "Conditionals. Second and third conditional",
        "Conditionals. Mixed conditionals",
        "Conditionals. Mixed conditionals in the past, present and future",
        "Conditionals. Wish",
        "Conditionals. Wish / if only, regrets",
        "Phrasal Verbs. Common phrasal verbs",
        "Phrasal Verbs. Extended phrasal verbs",
        "Phrasal Verbs. Extended phrasal verbs",
        "Phrasal Verbs. Extended phrasal verbs (splitting)",
        "Passives. Simple passive",
        "Passives. All passive forms",
        "Other Verb Forms. Reported speech (range of tenses)",
        "Other Verb Forms. Relative clauses",
        "Modals: Can. Can/can't (ability)",
        "Modals: Can. Can/could (functional)",
        "Modals: Possibility. Might, may",
        "Modals: Possibility. Possibly, probably, perhaps",
        "Modals: Possibility. Might, may, will, probably",
        "Modals: Possibility. Must/can't (deduction)",
        "Modals: Obligation and Necessity. Must/mustn't",
        "Modals: Obligation and Necessity. Have to",
        "Modals: Obligation and Necessity. Must/have to",
        "Modals: Obligation and Necessity. Should",
        "Modals: Obligation and Necessity. Ought to",
        "Modals: Obligation and Necessity. Need to/needn't",
        "Modals: Past. Deduction and speculation (should have, might have etc.)",
        "Modals: Past. Can't have, needn't have",
        "Nouns. Very common countable and uncountable (much/many)",
        "Nouns. Countable and uncountable (much/many)",
        "Nouns. There is / there are",
        "Pronouns. Personal - subject",
        "Possessives. Possessive adjectives",
        "Possessives. Use of 's and s'",
        "Possessives. Possessive pronouns",
        "Prepositions and Prepositional Phrases. Common prepositions",
        "Prepositions and Prepositional Phrases. Prepositional phrases (time and movement)",
        "Prepositions and Prepositional Phrases. Prepositions of time (on/at/in)",
        "Prepositions and Prepositional Phrases. Prepositional phrases (place, time and movement)",
        "Prepositions and Prepositional Phrases. Prepositions of place",
        "Articles. Definite, indefinite",
        "Articles. Zero article with uncountable nouns",
        "Articles. Definite article with superlatives",
        "Articles. With countable and uncountable nouns",
        "Articles. With abstract nouns",
        "Determiners. Basic (e.g. any, some, a lot of)",
        "Determiners. Wider range (e.g. all, none, not (any), enough, (a) few)",
        "Determiners. Broad range (e.g. all the, most, both)",
        "Adjectives. Common",
        "Adjectives. Demonstrative",
        "Adjectives. Ending in '-ed' and '-ing'",
        "Adjectives. Collocation of adjective",
        "Adjectives. Comparative, superlative",
        "Adjectives. Comparative, - use of than",
        "Adjectives. Superlative, - use of definite article",
        "Adjectives. Comparisons with fewer and less",
        "Adverbs. Adverbs of frequency",
        "Adverbs. Simple adverbs of place, manner and time",
        "Adverbs. Adverbial phrases of time, place and frequency, including word order",
        "Adverbs. (Adjectives and) adverbs",
        "Adverbs. Adverbial phrases of degree, extent, probability",
        "Adverbs. Comparative and superlative of adverbs",
        "Adverbs. Attitudinal adverbs",
        "Adverbs. Inversion (negative adverbials)",
        "Intensifiers. Very basic (very, really)",
        "Intensifiers. Basic (quite, so, a bit)",
        "Intensifiers. Broader range of intensifiers (such as too, so, enough)",
        "Intensifiers. Wide range (such as extremely, much too)",
        "Intensifiers. Collocation of intensifiers",
        "Lexis. Nationalities and countries",
        "Lexis. Personal information",
        "Lexis. Food and drink",
        "Lexis. Things in the town, shops and shopping",
        "Lexis. Travel and services vocabulary",
        "Lexis. Verbs, basic",
        "Lexis. Clothes",
        "Lexis. Colours",
        "Lexis. Dimensions",
        "Lexis. Ways of travelling",
        "Lexis. Objects and rooms",
        "Lexis. Adjectives: personality, description, feelings",
        "Lexis. Contrasting opinions (on the one hand . . . )",
        "Lexis. Summarising exponents (briefly, all in all . . . )",
        "Lexis. Collocation",
        "Lexis. Colloquial language",
        "Lexis. Approximating (vague language)",
        "Lexis. Differentiating to choose the best in context",
        "Lexis. Eliminating false friends",
        "Lexis. Formal and informal registers",
        "Lexis. Idiomatic expressions",
        "Topics. Family life",
        "Topics. Hobbies and pastimes",
        "Topics. Holidays",
        "Topics. Work and jobs",
        "Topics. Shopping",
        "Topics. Leisure activities",
        "Topics. Education",
        "Topics. Film",
        "Topics. Books and literature",
        "Topics. News, lifestyles and current affairs",
        "Topics. Media",
        "Topics. Arts",
        "Topics. Scientific development",
        "Topics. Technical and legal language"
    ];
}
